// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourGuideBD.Infrastructure.Persistence;

#nullable disable

namespace TourGuideBD.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621135245_AddPlaceOpeningClosingHours")]
    partial class AddPlaceOpeningClosingHours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Audit.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Location.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameBn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Districts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DivisionId = 1,
                            Name = "Dhaka",
                            NameBn = "ঢাকা"
                        },
                        new
                        {
                            Id = 2,
                            DivisionId = 1,
                            Name = "Faridpur",
                            NameBn = "ফরিদপুর"
                        },
                        new
                        {
                            Id = 3,
                            DivisionId = 1,
                            Name = "Gazipur",
                            NameBn = "গাজীপুর"
                        },
                        new
                        {
                            Id = 4,
                            DivisionId = 1,
                            Name = "Gopalganj",
                            NameBn = "গোপালগঞ্জ"
                        },
                        new
                        {
                            Id = 5,
                            DivisionId = 1,
                            Name = "Kishoreganj",
                            NameBn = "কিশোরগঞ্জ"
                        },
                        new
                        {
                            Id = 6,
                            DivisionId = 1,
                            Name = "Madaripur",
                            NameBn = "মাদারীপুর"
                        },
                        new
                        {
                            Id = 7,
                            DivisionId = 1,
                            Name = "Manikganj",
                            NameBn = "মানিকগঞ্জ"
                        },
                        new
                        {
                            Id = 8,
                            DivisionId = 1,
                            Name = "Munshiganj",
                            NameBn = "মুন্সিগঞ্জ"
                        },
                        new
                        {
                            Id = 9,
                            DivisionId = 1,
                            Name = "Narayanganj",
                            NameBn = "নারায়ণগঞ্জ"
                        },
                        new
                        {
                            Id = 10,
                            DivisionId = 1,
                            Name = "Narsingdi",
                            NameBn = "নরসিংদী"
                        },
                        new
                        {
                            Id = 11,
                            DivisionId = 1,
                            Name = "Rajbari",
                            NameBn = "রাজবাড়ী"
                        },
                        new
                        {
                            Id = 12,
                            DivisionId = 1,
                            Name = "Shariatpur",
                            NameBn = "শরীয়তপুর"
                        },
                        new
                        {
                            Id = 13,
                            DivisionId = 1,
                            Name = "Tangail",
                            NameBn = "টাঙ্গাইল"
                        },
                        new
                        {
                            Id = 14,
                            DivisionId = 2,
                            Name = "Bandarban",
                            NameBn = "বান্দরবান"
                        },
                        new
                        {
                            Id = 15,
                            DivisionId = 2,
                            Name = "Brahmanbaria",
                            NameBn = "ব্রাহ্মণবাড়িয়া"
                        },
                        new
                        {
                            Id = 16,
                            DivisionId = 2,
                            Name = "Chandpur",
                            NameBn = "চাঁদপুর"
                        },
                        new
                        {
                            Id = 17,
                            DivisionId = 2,
                            Name = "Chattogram",
                            NameBn = "চট্টগ্রাম"
                        },
                        new
                        {
                            Id = 18,
                            DivisionId = 2,
                            Name = "Cumilla",
                            NameBn = "কুমিল্লা"
                        },
                        new
                        {
                            Id = 19,
                            DivisionId = 2,
                            Name = "Cox's Bazar",
                            NameBn = "কক্সবাজার"
                        },
                        new
                        {
                            Id = 20,
                            DivisionId = 2,
                            Name = "Feni",
                            NameBn = "ফেনী"
                        },
                        new
                        {
                            Id = 21,
                            DivisionId = 2,
                            Name = "Khagrachhari",
                            NameBn = "খাগড়াছড়ি"
                        },
                        new
                        {
                            Id = 22,
                            DivisionId = 2,
                            Name = "Lakshmipur",
                            NameBn = "লক্ষ্মীপুর"
                        },
                        new
                        {
                            Id = 23,
                            DivisionId = 2,
                            Name = "Noakhali",
                            NameBn = "নোয়াখালী"
                        },
                        new
                        {
                            Id = 24,
                            DivisionId = 2,
                            Name = "Rangamati",
                            NameBn = "রাঙ্গামাটি"
                        },
                        new
                        {
                            Id = 25,
                            DivisionId = 3,
                            Name = "Bogura",
                            NameBn = "বগুড়া"
                        },
                        new
                        {
                            Id = 26,
                            DivisionId = 3,
                            Name = "Joypurhat",
                            NameBn = "জয়পুরহাট"
                        },
                        new
                        {
                            Id = 27,
                            DivisionId = 3,
                            Name = "Naogaon",
                            NameBn = "নওগাঁ"
                        },
                        new
                        {
                            Id = 28,
                            DivisionId = 3,
                            Name = "Natore",
                            NameBn = "নাটোর"
                        },
                        new
                        {
                            Id = 29,
                            DivisionId = 3,
                            Name = "Chapainawabganj",
                            NameBn = "চাঁপাইনবাবগঞ্জ"
                        },
                        new
                        {
                            Id = 30,
                            DivisionId = 3,
                            Name = "Pabna",
                            NameBn = "পাবনা"
                        },
                        new
                        {
                            Id = 31,
                            DivisionId = 3,
                            Name = "Rajshahi",
                            NameBn = "রাজশাহী"
                        },
                        new
                        {
                            Id = 32,
                            DivisionId = 3,
                            Name = "Sirajganj",
                            NameBn = "সিরাজগঞ্জ"
                        },
                        new
                        {
                            Id = 33,
                            DivisionId = 4,
                            Name = "Bagerhat",
                            NameBn = "বাগেরহাট"
                        },
                        new
                        {
                            Id = 34,
                            DivisionId = 4,
                            Name = "Chuadanga",
                            NameBn = "চুয়াডাঙ্গা"
                        },
                        new
                        {
                            Id = 35,
                            DivisionId = 4,
                            Name = "Jashore",
                            NameBn = "যশোর"
                        },
                        new
                        {
                            Id = 36,
                            DivisionId = 4,
                            Name = "Jhenaidah",
                            NameBn = "ঝিনাইদহ"
                        },
                        new
                        {
                            Id = 37,
                            DivisionId = 4,
                            Name = "Khulna",
                            NameBn = "খুলনা"
                        },
                        new
                        {
                            Id = 38,
                            DivisionId = 4,
                            Name = "Kushtia",
                            NameBn = "কুষ্টিয়া"
                        },
                        new
                        {
                            Id = 39,
                            DivisionId = 4,
                            Name = "Magura",
                            NameBn = "মাগুরা"
                        },
                        new
                        {
                            Id = 40,
                            DivisionId = 4,
                            Name = "Meherpur",
                            NameBn = "মেহেরপুর"
                        },
                        new
                        {
                            Id = 41,
                            DivisionId = 4,
                            Name = "Narail",
                            NameBn = "নড়াইল"
                        },
                        new
                        {
                            Id = 42,
                            DivisionId = 4,
                            Name = "Satkhira",
                            NameBn = "সাতক্ষীরা"
                        },
                        new
                        {
                            Id = 43,
                            DivisionId = 5,
                            Name = "Barguna",
                            NameBn = "বরগুনা"
                        },
                        new
                        {
                            Id = 44,
                            DivisionId = 5,
                            Name = "Barishal",
                            NameBn = "বরিশাল"
                        },
                        new
                        {
                            Id = 45,
                            DivisionId = 5,
                            Name = "Bhola",
                            NameBn = "ভোলা"
                        },
                        new
                        {
                            Id = 46,
                            DivisionId = 5,
                            Name = "Jhalokati",
                            NameBn = "ঝালকাঠি"
                        },
                        new
                        {
                            Id = 47,
                            DivisionId = 5,
                            Name = "Patuakhali",
                            NameBn = "পটুয়াখালী"
                        },
                        new
                        {
                            Id = 48,
                            DivisionId = 5,
                            Name = "Pirojpur",
                            NameBn = "পিরোজপুর"
                        },
                        new
                        {
                            Id = 49,
                            DivisionId = 6,
                            Name = "Habiganj",
                            NameBn = "হবিগঞ্জ"
                        },
                        new
                        {
                            Id = 50,
                            DivisionId = 6,
                            Name = "Moulvibazar",
                            NameBn = "মৌলভীবাজার"
                        },
                        new
                        {
                            Id = 51,
                            DivisionId = 6,
                            Name = "Sunamganj",
                            NameBn = "সুনামগঞ্জ"
                        },
                        new
                        {
                            Id = 52,
                            DivisionId = 6,
                            Name = "Sylhet",
                            NameBn = "সিলেট"
                        },
                        new
                        {
                            Id = 53,
                            DivisionId = 7,
                            Name = "Dinajpur",
                            NameBn = "দিনাজপুর"
                        },
                        new
                        {
                            Id = 54,
                            DivisionId = 7,
                            Name = "Gaibandha",
                            NameBn = "গাইবান্ধা"
                        },
                        new
                        {
                            Id = 55,
                            DivisionId = 7,
                            Name = "Kurigram",
                            NameBn = "কুড়িগ্রাম"
                        },
                        new
                        {
                            Id = 56,
                            DivisionId = 7,
                            Name = "Lalmonirhat",
                            NameBn = "লালমনিরহাট"
                        },
                        new
                        {
                            Id = 57,
                            DivisionId = 7,
                            Name = "Nilphamari",
                            NameBn = "নীলফামারী"
                        },
                        new
                        {
                            Id = 58,
                            DivisionId = 7,
                            Name = "Panchagarh",
                            NameBn = "পঞ্চগড়"
                        },
                        new
                        {
                            Id = 59,
                            DivisionId = 7,
                            Name = "Rangpur",
                            NameBn = "রংপুর"
                        },
                        new
                        {
                            Id = 60,
                            DivisionId = 7,
                            Name = "Thakurgaon",
                            NameBn = "ঠাকুরগাঁও"
                        },
                        new
                        {
                            Id = 61,
                            DivisionId = 8,
                            Name = "Jamalpur",
                            NameBn = "জামালপুর"
                        },
                        new
                        {
                            Id = 62,
                            DivisionId = 8,
                            Name = "Mymensingh",
                            NameBn = "ময়মনসিংহ"
                        },
                        new
                        {
                            Id = 63,
                            DivisionId = 8,
                            Name = "Netrokona",
                            NameBn = "নেত্রকোণা"
                        },
                        new
                        {
                            Id = 64,
                            DivisionId = 8,
                            Name = "Sherpur",
                            NameBn = "শেরপুর"
                        });
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Location.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameBn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Divisions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dhaka",
                            NameBn = "ঢাকা"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chattogram",
                            NameBn = "চট্টগ্রাম"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rajshahi",
                            NameBn = "রাজশাহী"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Khulna",
                            NameBn = "খুলনা"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Barishal",
                            NameBn = "বরিশাল"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sylhet",
                            NameBn = "সিলেট"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rangpur",
                            NameBn = "রংপুর"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mymensingh",
                            NameBn = "ময়মনসিংহ"
                        });
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Location.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("BestSeason")
                        .HasColumnType("int");

                    b.Property<string>("ClosingHours")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<decimal>("EntryFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameBn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubmittedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<int?>("UpazilaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("DistrictId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("Name");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("UpazilaId");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("Places", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Location.Upazila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameBn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId", "Name")
                        .IsUnique();

                    b.ToTable("Upazilas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistrictId = 19,
                            Name = "Cox's Bazar Sadar",
                            NameBn = "কক্সবাজার সদর"
                        },
                        new
                        {
                            Id = 2,
                            DistrictId = 19,
                            Name = "Teknaf",
                            NameBn = "টেকনাফ"
                        },
                        new
                        {
                            Id = 3,
                            DistrictId = 19,
                            Name = "Ramu",
                            NameBn = "রামু"
                        },
                        new
                        {
                            Id = 4,
                            DistrictId = 19,
                            Name = "Ukhia",
                            NameBn = "উখিয়া"
                        },
                        new
                        {
                            Id = 5,
                            DistrictId = 19,
                            Name = "Maheshkhali",
                            NameBn = "মহেশখালী"
                        },
                        new
                        {
                            Id = 6,
                            DistrictId = 14,
                            Name = "Bandarban Sadar",
                            NameBn = "বান্দরবান সদর"
                        },
                        new
                        {
                            Id = 7,
                            DistrictId = 14,
                            Name = "Thanchi",
                            NameBn = "থানচি"
                        },
                        new
                        {
                            Id = 8,
                            DistrictId = 14,
                            Name = "Ruma",
                            NameBn = "রুমা"
                        },
                        new
                        {
                            Id = 9,
                            DistrictId = 14,
                            Name = "Lama",
                            NameBn = "লামা"
                        },
                        new
                        {
                            Id = 10,
                            DistrictId = 24,
                            Name = "Rangamati Sadar",
                            NameBn = "রাঙ্গামাটি সদর"
                        },
                        new
                        {
                            Id = 11,
                            DistrictId = 24,
                            Name = "Kaptai",
                            NameBn = "কাপ্তাই"
                        },
                        new
                        {
                            Id = 12,
                            DistrictId = 24,
                            Name = "Baghaichhari",
                            NameBn = "বাঘাইছড়ি"
                        },
                        new
                        {
                            Id = 13,
                            DistrictId = 46,
                            Name = "Sylhet Sadar",
                            NameBn = "সিলেট সদর"
                        },
                        new
                        {
                            Id = 14,
                            DistrictId = 46,
                            Name = "Jaintiapur",
                            NameBn = "জৈন্তাপুর"
                        },
                        new
                        {
                            Id = 15,
                            DistrictId = 46,
                            Name = "Companiganj",
                            NameBn = "কোম্পানীগঞ্জ"
                        },
                        new
                        {
                            Id = 16,
                            DistrictId = 46,
                            Name = "Gowainghat",
                            NameBn = "গোয়াইনঘাট"
                        },
                        new
                        {
                            Id = 17,
                            DistrictId = 45,
                            Name = "Sreemangal",
                            NameBn = "শ্রীমঙ্গল"
                        },
                        new
                        {
                            Id = 18,
                            DistrictId = 45,
                            Name = "Moulvibazar Sadar",
                            NameBn = "মৌলভীবাজার সদর"
                        },
                        new
                        {
                            Id = 19,
                            DistrictId = 45,
                            Name = "Kamalganj",
                            NameBn = "কমলগঞ্জ"
                        },
                        new
                        {
                            Id = 20,
                            DistrictId = 13,
                            Name = "Tangail Sadar",
                            NameBn = "টাঙ্গাইল সদর"
                        },
                        new
                        {
                            Id = 21,
                            DistrictId = 13,
                            Name = "Madhupur",
                            NameBn = "মধুপুর"
                        },
                        new
                        {
                            Id = 22,
                            DistrictId = 13,
                            Name = "Ghatail",
                            NameBn = "ঘাটাইল"
                        },
                        new
                        {
                            Id = 23,
                            DistrictId = 25,
                            Name = "Bogura Sadar",
                            NameBn = "বগুড়া সদর"
                        },
                        new
                        {
                            Id = 24,
                            DistrictId = 25,
                            Name = "Shibganj",
                            NameBn = "শিবগঞ্জ"
                        },
                        new
                        {
                            Id = 25,
                            DistrictId = 25,
                            Name = "Mahasthangarh (Shibganj area)",
                            NameBn = "মহাস্থানগড়"
                        },
                        new
                        {
                            Id = 26,
                            DistrictId = 31,
                            Name = "Rajshahi Sadar",
                            NameBn = "রাজশাহী সদর"
                        },
                        new
                        {
                            Id = 27,
                            DistrictId = 31,
                            Name = "Paba",
                            NameBn = "পবা"
                        },
                        new
                        {
                            Id = 28,
                            DistrictId = 31,
                            Name = "Bagha",
                            NameBn = "বাঘা"
                        },
                        new
                        {
                            Id = 29,
                            DistrictId = 56,
                            Name = "Dinajpur Sadar",
                            NameBn = "দিনাজপুর সদর"
                        },
                        new
                        {
                            Id = 30,
                            DistrictId = 56,
                            Name = "Kantanagar (Kaharole)",
                            NameBn = "কাহারোল"
                        },
                        new
                        {
                            Id = 31,
                            DistrictId = 35,
                            Name = "Khulna Sadar",
                            NameBn = "খুলনা সদর"
                        },
                        new
                        {
                            Id = 32,
                            DistrictId = 35,
                            Name = "Dumuria",
                            NameBn = "ডুমুরিয়া"
                        },
                        new
                        {
                            Id = 33,
                            DistrictId = 35,
                            Name = "Koyra (Sundarbans)",
                            NameBn = "কয়রা"
                        },
                        new
                        {
                            Id = 34,
                            DistrictId = 33,
                            Name = "Jashore Sadar",
                            NameBn = "যশোর সদর"
                        },
                        new
                        {
                            Id = 35,
                            DistrictId = 33,
                            Name = "Jhikargacha",
                            NameBn = "ঝিকরগাছা"
                        },
                        new
                        {
                            Id = 36,
                            DistrictId = 42,
                            Name = "Barishal Sadar",
                            NameBn = "বরিশাল সদর"
                        },
                        new
                        {
                            Id = 37,
                            DistrictId = 42,
                            Name = "Bakerganj",
                            NameBn = "বাকেরগঞ্জ"
                        },
                        new
                        {
                            Id = 38,
                            DistrictId = 44,
                            Name = "Patuakhali Sadar",
                            NameBn = "পটুয়াখালী সদর"
                        },
                        new
                        {
                            Id = 39,
                            DistrictId = 44,
                            Name = "Kuakata (Kalapara)",
                            NameBn = "কলাপাড়া"
                        });
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.PlaceDetails.PlaceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryType")
                        .IsUnique();

                    b.ToTable("PlaceCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryType = 1,
                            Name = "Beach"
                        },
                        new
                        {
                            Id = 2,
                            CategoryType = 2,
                            Name = "Hill"
                        },
                        new
                        {
                            Id = 3,
                            CategoryType = 3,
                            Name = "Forest"
                        },
                        new
                        {
                            Id = 4,
                            CategoryType = 4,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 5,
                            CategoryType = 5,
                            Name = "Religious"
                        },
                        new
                        {
                            Id = 6,
                            CategoryType = 6,
                            Name = "Waterfall"
                        });
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.PlaceDetails.PlaceCategoryMap", b =>
                {
                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("PlaceCategoryId")
                        .HasColumnType("int");

                    b.HasKey("PlaceId", "PlaceCategoryId");

                    b.HasIndex("PlaceCategoryId");

                    b.ToTable("PlaceCategoryMaps", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.PlaceDetails.PlacePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("PlacePhotos", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.PlaceDetails.PlaceTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("Tag");

                    b.ToTable("PlaceTags", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Realtime.Broadcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SentByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Broadcasts", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Realtime.LiveVisitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrowdLevel")
                        .HasColumnType("int");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId")
                        .IsUnique();

                    b.ToTable("LiveVisitors", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Realtime.WeatherAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId", "IsActive");

                    b.ToTable("WeatherAlerts", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentBn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CommentEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeratorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeratorNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("PlaceId", "Status");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Reviews.ReviewPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewPhotos", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Reviews.ReviewReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ReportedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ResolvedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("Status");

                    b.ToTable("ReviewReports", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Trip.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedFoodCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("EstimatedTotalCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Itineraries", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Trip.ItineraryStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DistanceFromPreviousKm")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("EntryFeeAtThisStop")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<decimal>("TransportCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TransportTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TravelTimeMinutes")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TransportTypeId");

                    b.ToTable("ItineraryStops", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Trip.TransportRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageSpeedKmh")
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumFare")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("RatePerKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TransportTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransportTypeId");

                    b.ToTable("TransportRates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageSpeedKmh = 40m,
                            IsActive = true,
                            MinimumFare = 20m,
                            RatePerKm = 1.80m,
                            TransportTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            AverageSpeedKmh = 25m,
                            IsActive = true,
                            MinimumFare = 50m,
                            RatePerKm = 8.00m,
                            TransportTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            AverageSpeedKmh = 50m,
                            IsActive = true,
                            MinimumFare = 30m,
                            RatePerKm = 1.20m,
                            TransportTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            AverageSpeedKmh = 15m,
                            IsActive = true,
                            MinimumFare = 50m,
                            RatePerKm = 5.00m,
                            TransportTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            AverageSpeedKmh = 45m,
                            IsActive = true,
                            MinimumFare = 100m,
                            RatePerKm = 15.00m,
                            TransportTypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            AverageSpeedKmh = 35m,
                            IsActive = true,
                            MinimumFare = 20m,
                            RatePerKm = 4.00m,
                            TransportTypeId = 6
                        });
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Trip.TransportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("TransportTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bus",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "CNG",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Train",
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Boat",
                            Type = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Car",
                            Type = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bike",
                            Type = 6
                        });
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentRefreshTokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Users.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("UserId");

                    b.ToTable("CheckIns", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Users.FavouritePlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("UserId", "PlaceId")
                        .IsUnique();

                    b.ToTable("FavouritePlaces", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Users.SavedDistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("UserId", "DistrictId")
                        .IsUnique();

                    b.ToTable("SavedDistricts", (string)null);
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Users.VisitHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("UserId");

                    b.ToTable("VisitHistories", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourGuideBD.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Location.District", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.Division", "Division")
                        .WithMany("Districts")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Location.Place", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.District", "District")
                        .WithMany("Places")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourGuideBD.Domain.Entities.Location.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourGuideBD.Domain.Entities.Users.ApplicationUser", "SubmittedByUser")
                        .WithMany("SubmittedPlaces")
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TourGuideBD.Domain.Entities.Location.Upazila", "Upazila")
                        .WithMany("Places")
                        .HasForeignKey("UpazilaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("District");

                    b.Navigation("Division");

                    b.Navigation("SubmittedByUser");

                    b.Navigation("Upazila");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Location.Upazila", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.District", "District")
                        .WithMany("Upazilas")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.PlaceDetails.PlaceCategoryMap", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.PlaceDetails.PlaceCategory", "PlaceCategory")
                        .WithMany("CategoryMaps")
                        .HasForeignKey("PlaceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourGuideBD.Domain.Entities.Location.Place", "Place")
                        .WithMany("CategoryMaps")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("PlaceCategory");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.PlaceDetails.PlacePhoto", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.Place", "Place")
                        .WithMany("Photos")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.PlaceDetails.PlaceTag", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.Place", "Place")
                        .WithMany("Tags")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Realtime.Broadcast", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("District");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Realtime.LiveVisitor", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Realtime.WeatherAlert", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.Place", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourGuideBD.Domain.Entities.Users.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Reviews.ReviewPhoto", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Reviews.Review", "Review")
                        .WithMany("Photos")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Reviews.ReviewReport", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Users.ApplicationUser", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourGuideBD.Domain.Entities.Reviews.Review", "Review")
                        .WithMany("Reports")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedByUser");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Trip.Itinerary", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Users.ApplicationUser", "User")
                        .WithMany("Itineraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Trip.ItineraryStop", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Trip.Itinerary", "Itinerary")
                        .WithMany("Stops")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourGuideBD.Domain.Entities.Location.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourGuideBD.Domain.Entities.Trip.TransportType", "TransportType")
                        .WithMany()
                        .HasForeignKey("TransportTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Itinerary");

                    b.Navigation("Place");

                    b.Navigation("TransportType");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Trip.TransportRate", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Trip.TransportType", "TransportType")
                        .WithMany("Rates")
                        .HasForeignKey("TransportTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportType");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Users.CheckIn", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourGuideBD.Domain.Entities.Users.ApplicationUser", "User")
                        .WithMany("CheckIns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Users.FavouritePlace", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourGuideBD.Domain.Entities.Users.ApplicationUser", "User")
                        .WithMany("FavouritePlaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Users.SavedDistrict", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourGuideBD.Domain.Entities.Users.ApplicationUser", "User")
                        .WithMany("SavedDistricts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Users.VisitHistory", b =>
                {
                    b.HasOne("TourGuideBD.Domain.Entities.Location.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourGuideBD.Domain.Entities.Users.ApplicationUser", "User")
                        .WithMany("VisitHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Location.District", b =>
                {
                    b.Navigation("Places");

                    b.Navigation("Upazilas");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Location.Division", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Location.Place", b =>
                {
                    b.Navigation("CategoryMaps");

                    b.Navigation("Photos");

                    b.Navigation("Reviews");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Location.Upazila", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.PlaceDetails.PlaceCategory", b =>
                {
                    b.Navigation("CategoryMaps");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Reviews.Review", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Trip.Itinerary", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Trip.TransportType", b =>
                {
                    b.Navigation("Rates");
                });

            modelBuilder.Entity("TourGuideBD.Domain.Entities.Users.ApplicationUser", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("FavouritePlaces");

                    b.Navigation("Itineraries");

                    b.Navigation("Reviews");

                    b.Navigation("SavedDistricts");

                    b.Navigation("SubmittedPlaces");

                    b.Navigation("VisitHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
